export type TradeRecapMistakeGroup = {
  group: string;
  mistakes: string[];
};

export const TRADE_RECAP_MISTAKE_GROUPS: TradeRecapMistakeGroup[] = [
  {
    group: "Emotional Mistakes",
    mistakes: [
      "FOMO entry",
      "Revenge trade",
      "Boredom trade",
      "Fear-based exit",
      "Greed hold",
      "Hope hold",
      "Panic close",
      "Hesitated too long",
      "Forced the trade",
      "Overconfidence",
      "Low confidence",
      "Tried to make it back",
      "Ignored gut feeling",
      "Traded while frustrated",
      "Traded while tired",
      "Traded while distracted",
      "Chased price",
      "Could not accept being wrong",
      "Held because of ego",
      "Exited because of impatience",
    ],
  },
  {
    group: "Trade Entry Mistakes",
    mistakes: [
      "Entered too early",
      "Entered too late",
      "Entered without confirmation",
      "Entered into resistance",
      "Entered into support",
      "Bad entry location",
      "Missed better entry",
      "Entered after move was extended",
      "Entered during chop",
      "Entered during fakeout",
      "Entered before candle close",
      "Poor limit order placement",
      "Market order instead of planned limit",
      "Entered with weak confluence",
      "Entered against setup rules",
      "Entered after missing original setup",
      "Entered in no-trade zone",
      "Entered during spread spike",
    ],
  },
  {
    group: "Trading Plan / Risk Management Mistakes",
    mistakes: [
      "Over-risked",
      "Position too large",
      "No stop loss",
      "Stop loss too wide",
      "Stop loss too tight",
      "Moved stop loss wider",
      "Did not follow risk plan",
      "Took too many trades",
      "Broke max daily loss",
      "Broke max trade count",
      "Risk/reward too weak",
      "Added to losing trade",
      "Averaged down",
      "Ignored account drawdown",
      "Risked more after a loss",
      "Risked more after a win",
      "Did not calculate position size",
      "Took trade without defined invalidation",
      "Ignored max losing streak rule",
    ],
  },
  {
    group: "Trade Management Mistakes",
    mistakes: [
      "Closed too early",
      "Held too long",
      "Did not take partials",
      "Took partials too early",
      "Did not move stop when planned",
      "Moved stop too soon",
      "Let winner turn into loser",
      "Did not trail stop",
      "Managed based on emotion",
      "Changed plan mid-trade",
      "Ignored invalidation",
      "Added without plan",
      "Scaled out without reason",
      "Scaled in without confirmation",
      "Did not protect profit",
      "Overmanaged the trade",
      "Undermanaged the trade",
    ],
  },
  {
    group: "Exit Mistakes",
    mistakes: [
      "Exit without reason",
      "Missed planned target",
      "Took profit too early",
      "Did not respect take profit",
      "Stayed in after setup failed",
      "Exited during normal pullback",
      "Closed because of fear",
      "Closed because of one candle",
      "No exit plan",
      "Exit was reactive",
      "Ignored exit signal",
      "Did not close at invalidation",
      "Closed before key level was reached",
      "Waited for unrealistic target",
      "Let stop loss hit after clear failure",
    ],
  },
  {
    group: "Analysis Mistakes",
    mistakes: [
      "Wrong market direction",
      "Missed higher timeframe trend",
      "Ignored key level",
      "Bad support/resistance read",
      "Misread structure",
      "Ignored liquidity area",
      "Ignored news",
      "Ignored spread",
      "Ignored volatility",
      "Poor confluence",
      "Confirmation bias",
      "Chart was unclear",
      "Ignored market context",
      "Missed trendline break",
      "Misread pullback",
      "Misread breakout",
      "Misread fakeout",
      "Ignored range conditions",
      "Ignored correlation",
    ],
  },
  {
    group: "Rule-Breaking Mistakes",
    mistakes: [
      "Broke entry rule",
      "Broke exit rule",
      "Broke session rule",
      "Broke strategy rule",
      "Broke news rule",
      "Broke risk rule",
      "Traded outside plan",
      "Took unplanned setup",
      "Ignored checklist",
      "Did not journal before trade",
      "Skipped pre-trade plan",
      "Skipped confirmation rule",
      "Ignored no-trade rule",
      "Ignored max trades rule",
      "Ignored cooldown rule",
    ],
  },
  {
    group: "Discipline / Process Mistakes",
    mistakes: [
      "Did not wait",
      "Did not prepare",
      "No pre-trade analysis",
      "Did not screenshot",
      "Did not review previous trades",
      "Rushed decision",
      "Multitasking",
      "Poor focus",
      "Traded at bad time",
      "Did not follow routine",
      "Skipped checklist",
      "Late to chart",
      "Poor trade notes",
      "Incomplete trade plan",
      "Did not review session conditions",
      "Ignored previous mistake pattern",
    ],
  },
  {
    group: "Market Condition Mistakes",
    mistakes: [
      "Traded low volume",
      "Traded high spread",
      "Traded during news",
      "Traded during consolidation",
      "Traded against strong trend",
      "Traded in messy price action",
      "Traded during session transition",
      "Ignored market open volatility",
      "Ignored end-of-day conditions",
      "Traded during poor liquidity",
      "Traded during whipsaw",
      "Traded after major move finished",
      "Traded before market direction was clear",
    ],
  },
  {
    group: "Technical / Execution Mistakes",
    mistakes: [
      "Wrong lot size",
      "Wrong direction clicked",
      "Wrong pair selected",
      "Wrong stop placement",
      "Wrong take-profit placement",
      "Late order execution",
      "Accidental market order",
      "Platform mistake",
      "Did not check order details",
      "Slippage not considered",
      "Order not cancelled",
      "Duplicate order",
      "Entry price typed wrong",
      "Stop loss typed wrong",
      "Take profit typed wrong",
      "Forgot commission/spread cost",
    ],
  },
];

export const TRADE_RECAP_QUICK_MISTAKES = [
  "Entered too early",
  "Entered too late",
  "Entered without confirmation",
  "Over-risked",
  "Moved stop loss wider",
  "Closed too early",
  "Forced the trade",
  "Traded during news",
];
